### ISSUE TITLE
Fine-ET results

### ISSUE THREAD

**Issue by alejandrojcastaneira** [abhipec/HAnDS#1]
Hello,

First of all, congratulations on the great work!

I am doing some research on the Fine-ET setting using the 1k-WFB-g dataset.

I notice that in the paper the results for the whole Fine-ER pipeline are published, but I couldn't find the results from the Fine-ET subtask in isolation. Would be possible to share these results?

Best regards

**Comment by abhipec** [comment]
Hello @alejandrojcastaneira 

I hope this helps:

|Dataset| Strict | macro | micro | strict | macro | micro |
| --- | --- | --- | --- | --- | --- | --- | 
Wiki-FbF |  61.96 | 79.13 | 78.89 |  62.88 | 78.92 | 75.82
Wiki-NDS |  63.12 | 78.21 | 78.27 |  61.1 | 78.28 | 75.69
Wiki-FbF-w/o-3   |  63.79 | 79.29 | 79.16 |  63.94 | 80.11 | 77.38

Column 2-4 for the FIGER test set and column 5-7 for the 1k-WFB-g dataset.
